export const metadata = {
  title: 'Flexibol',
  description: 'Generated by Next.js',
  icons: {
    icon: 'https://res.cloudinary.com/dvda6isym/image/upload/v1711248696/favicon_xizcjk.ico',
    apple: 'https://res.cloudinary.com/dvda6isym/image/upload/v1711248696/favicon_xizcjk.ico'
  }
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
      <link rel="icon" href="/favicon.ico" sizes="any" />
      </head>
      <body>{children}</body>
    </html>
  )
}
